### ISSUE TITLE
Why a new language?

### ISSUE THREAD

**Issue by notslang** [nporteschaikin/sneak#9]
Ok, I read the readme, but I still don't get it: why did you write an entire "Jade clone" just to add tumblr development features, when Jade has a full mixin system? Or, if mixins weren't enough (which is rare, but possible), why didn't you just use Jade to parse sneak files, but then take the AST and output everything in a slightly customized way? Jade has a really well tested parsing system, and the code isn't even hard to understand. Or if the Jade AST wasn't enough, why not fork Jade? Or if you really didn't like TJ & forbes' code, why not build on an existing, well tested parser like [Jison](http://zaach.github.io/jison/)?

There are just so many alternatives to building a totally new language, that are normally more preferable because building atop an existing project lets you:
- reuse functionality and reduce your codebase/development time
- increase the reliability of your library because its underlying components are well-tested (jade has ~200 tests and thousands of users)
- reduce the learning curve for using your language (a lot of people already know jade**, so it's much easier to learn a language that "adds X features to jade" than learn one that "was inspired by jade, but has it's own slightly different syntax")

So, I'm curious as to what the reasons behind this design are.

---

*\* there's even a really well written set of [documentation](http://www.packtpub.com/create-dynamic-web-pages-using-jade/book) for it :wink:

**Comment by zspecza** [comment]
psht, to gain street cred of course

**Comment by notslang** [comment]
haha, excellent reason... :laughing:

**Comment by nporteschaikin** [comment]
@slang800 @declandewet This seemed like the most obvious solution to the problem I was trying to solve and it does just that.  I'm intent on continuing to hammer away at this; as I become more familiar with the problem, I may conclude that writing on top of Jade is more pragmatic and scrap sneak.

Moreover, it's been a substantial learning experience for me.  And if nobody ever attempted to re-write anything, we'd still be writing code in Assembly.  I'm sure you've reinvented the wheel once or twice, no?  :wink:

**Comment by jescalan** [comment]
Yeah we did discuss this in the dev room for a bit, I think a good piece of it was the learning experience, which is legit.

**Comment by notslang** [comment]
Ah, yeah - if you've never written a parser before, then that's a fantastic learning experience. And I don't think I've ever intentionally reinvented the wheel, but I've totally done projects just for fun, like [evenLESS](https://github.com/slang800/evenLESS) and [PATH](https://github.com/slang800/path) (which are both marked as dead now).
